package auth

type Authenticator interface {
	// Generate creates a hashed password and salt as output
	Generate(password string) (string, string)

	// Verify checks if hashed_password is generated by password and salt
	Verify(password string, salt string, hashed_password string) bool
}
